image: node:6.10

before_script:
  - npm install

stages:
  - test
  - build

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run clean
    - npm run build-api
    - npm run build-client
  only:
    - master
