export const FIREBASE_CONFIG_REQUEST = 'FIREBASE_CONFIG_REQUEST';
export const FIREBASE_CONFIG_SUCCESS = 'FIREBASE_CONFIG_SUCCESS';
export const FIREBASE_CONFIG_FAILURE = 'FIREBASE_CONFIG_FAILURE';

export const FB_USER_DATA_REQUEST = 'FB_USER_DATA_REQUEST';
export const FB_USER_DATA_SUCCESS = 'FB_USER_DATA_SUCCESS';
export const FB_USER_DATA_FAILURE = 'FB_USER_DATA_FAILURE';
