export const FIREBASE_CONFIG_REQUEST = 'FIREBASE_CONFIG_REQUEST';
export const FIREBASE_CONFIG_SUCCESS = 'FIREBASE_CONFIG_SUCCESS';
export const FIREBASE_CONFIG_FAILURE = 'FIREBASE_CONFIG_FAILURE';

export const FB_USER_DATA_REQUEST = 'FB_USER_DATA_REQUEST';
export const FB_USER_DATA_SUCCESS = 'FB_USER_DATA_SUCCESS';
export const FB_USER_DATA_FAILURE = 'FB_USER_DATA_FAILURE';

export const DB_USER_DATA_REQUEST = 'DB_USER_DATA_REQUEST';
export const DB_USER_DATA_SUCCESS = 'DB_USER_DATA_SUCCESS';
export const DB_USER_DATA_FAILURE = 'DB_USER_DATA_FAILURE';

export const SAVE_CORRELATED_REQUEST = 'SAVE_CORRELATED_REQUEST';
export const SAVE_CORRELATED_SUCCESS = 'SAVE_CORRELATED_SUCCESS';
export const SAVE_CORRELATED_FAILURE = 'SAVE_CORRELATED_FAILURE';

export const SAVE_MASS_CORRELATED_REQUEST = 'SAVE_MASS_CORRELATED_REQUEST';
export const SAVE_MASS_CORRELATED_SUCCESS = 'SAVE_MASS_CORRELATED_SUCCESS';
export const SAVE_MASS_CORRELATED_FAILURE = 'SAVE_MASS_CORRELATED_FAILURE';
