export const SNAPPED_POINTS_SUCCESS = 'SNAPPED_POINTS_SUCCESS';
export const SNAPPED_POINTS_FAILURE = 'SNAPPED_POINTS_FAILURE';
export const SNAPPED_POINTS_REQUEST = 'SNAPPED_POINTS_REQUEST';

export const PLACE_DETAILS_REQUEST = 'PLACE_DETAILS_REQUEST';
export const PLACE_DETAILS_SUCCESS = 'PLACE_DETAILS_SUCCESS';
export const PLACE_DETAILS_FAILURE = 'PLACE_DETAILS_FAILURE';
